{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-common",
    "version": "7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "databinding-common-7.0.1.jar",
          "url": "databinding-common-7.0.1.jar",
          "size": 16103,
          "sha512": "ad1228c4e6ae9a973140bcc30dca3a9f9e074a9aef0388c049700501b14c943c7c9e89c394d5a791737ee1b314cbdf9fc84c8811f263ec57bacb515922bfa3e2",
          "sha256": "605514f0a525e0bae51d8e1a414a4bc4ccac51d0a3c4843fe720897dc89c7c15",
          "sha1": "30677a036df66005a08bb167620e6fc1f557bf0d",
          "md5": "dc112675a5d350a9cca7c320c46a5115"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.1.jar",
          "url": "databinding-common-7.0.1.jar",
          "size": 16103,
          "sha512": "ad1228c4e6ae9a973140bcc30dca3a9f9e074a9aef0388c049700501b14c943c7c9e89c394d5a791737ee1b314cbdf9fc84c8811f263ec57bacb515922bfa3e2",
          "sha256": "605514f0a525e0bae51d8e1a414a4bc4ccac51d0a3c4843fe720897dc89c7c15",
          "sha1": "30677a036df66005a08bb167620e6fc1f557bf0d",
          "md5": "dc112675a5d350a9cca7c320c46a5115"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.1-javadoc.jar",
          "url": "databinding-common-7.0.1-javadoc.jar",
          "size": 451434,
          "sha512": "3284804a3710eeaacede289a2ee04cf6a819a183abdbd49661b94acf095e5a5b3d8a19396cb4ba89699d46303e8f72bfe9eacad67532187d9b50dc6a3298531e",
          "sha256": "245bbc1f33bbad2e218a791b565a9417195b127a5d0bc85deba4fe3925266a02",
          "sha1": "40e1eefc3478e8b1cdf4ce6b496e264581c9ac3b",
          "md5": "78fd165334046e11eb0f6d923f2cfc2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "databinding-common-7.0.1-sources.jar",
          "url": "databinding-common-7.0.1-sources.jar",
          "size": 45950,
          "sha512": "b7f1c9bf415e4a980d7400be4476d83c839a008c281754c236ee61c0d5cc62f50caa05825633aff1afd0e2b7dc0954d0423a2acbcb6134cbe8b322eca40c4335",
          "sha256": "363e027f9f6a8c7e3b1b270e9e957d7e7574083cbfbd71f919fc45c58cf413ba",
          "sha1": "63514d597a81bf2314f41a316beb2fe6fae53371",
          "md5": "73a14d3b87f8fc65e765c14254cee676"
        }
      ]
    }
  ]
}
